{"url": "https://api.github.com/repos/datalad/datalad/issues/1128", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/1128/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/1128/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/1128/events", "html_url": "https://github.com/datalad/datalad/issues/1128", "id": 191553109, "node_id": "MDU6SXNzdWUxOTE1NTMxMDk=", "number": 1128, "title": "Bug on \"datalad get\" python version 3.5", "user": {"login": "demianw", "id": 272705, "node_id": "MDQ6VXNlcjI3MjcwNQ==", "avatar_url": "https://avatars.githubusercontent.com/u/272705?v=4", "gravatar_id": "", "url": "https://api.github.com/users/demianw", "html_url": "https://github.com/demianw", "followers_url": "https://api.github.com/users/demianw/followers", "following_url": "https://api.github.com/users/demianw/following{/other_user}", "gists_url": "https://api.github.com/users/demianw/gists{/gist_id}", "starred_url": "https://api.github.com/users/demianw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/demianw/subscriptions", "organizations_url": "https://api.github.com/users/demianw/orgs", "repos_url": "https://api.github.com/users/demianw/repos", "events_url": "https://api.github.com/users/demianw/events{/privacy}", "received_events_url": "https://api.github.com/users/demianw/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 440544386, "node_id": "MDU6TGFiZWw0NDA1NDQzODY=", "url": "https://api.github.com/repos/datalad/datalad/labels/fix-implemented", "name": "fix-implemented", "color": "0e8a16", "default": false, "description": "A fix is available, but has not been merged or released, yet."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": {"url": "https://api.github.com/repos/datalad/datalad/milestones/37", "html_url": "https://github.com/datalad/datalad/milestone/37", "labels_url": "https://api.github.com/repos/datalad/datalad/milestones/37/labels", "id": 2123515, "node_id": "MDk6TWlsZXN0b25lMjEyMzUxNQ==", "number": 37, "title": "Release 0.4.2", "description": "was never released -- will be absorbed into 0.5", "creator": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "open_issues": 0, "closed_issues": 12, "state": "closed", "created_at": "2016-11-09T01:12:36Z", "updated_at": "2017-02-09T16:13:36Z", "due_on": null, "closed_at": "2017-02-09T16:13:13Z"}, "comments": 6, "created_at": "2016-11-24T15:58:57Z", "updated_at": "2016-11-25T19:49:44Z", "closed_at": "2016-11-25T19:49:44Z", "author_association": "NONE", "active_lock_reason": null, "body": "When I try to execute \"datalad get\" on python 3.5 I get the error \r\n`[ERROR  ] unorderable types: tuple() < list() [version.py:_cmp:173] (TypeError)`\r\n\r\nThis doesn't happen when datalad is run from a python 2.7 interpreter\r\n\r\nThanks for this tool!", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/1128/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/1128/timeline", "performed_via_github_app": null}