{"url": "https://api.github.com/repos/datalad/datalad/issues/2545", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/2545/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/2545/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/2545/events", "html_url": "https://github.com/datalad/datalad/issues/2545", "id": 325962301, "node_id": "MDU6SXNzdWUzMjU5NjIzMDE=", "number": 2545, "title": "RI handling fails on Windows", "user": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 188141023, "node_id": "MDU6TGFiZWwxODgxNDEwMjM=", "url": "https://api.github.com/repos/datalad/datalad/labels/platform-windows", "name": "platform-windows", "color": "0052cc", "default": false, "description": "Issue concerned with Windows"}, {"id": 440544386, "node_id": "MDU6TGFiZWw0NDA1NDQzODY=", "url": "https://api.github.com/repos/datalad/datalad/labels/fix-implemented", "name": "fix-implemented", "color": "0e8a16", "default": false, "description": "A fix is available, but has not been merged or released, yet."}], "state": "closed", "locked": false, "assignee": {"login": "bpoldrack", "id": 10498301, "node_id": "MDQ6VXNlcjEwNDk4MzAx", "avatar_url": "https://avatars.githubusercontent.com/u/10498301?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bpoldrack", "html_url": "https://github.com/bpoldrack", "followers_url": "https://api.github.com/users/bpoldrack/followers", "following_url": "https://api.github.com/users/bpoldrack/following{/other_user}", "gists_url": "https://api.github.com/users/bpoldrack/gists{/gist_id}", "starred_url": "https://api.github.com/users/bpoldrack/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bpoldrack/subscriptions", "organizations_url": "https://api.github.com/users/bpoldrack/orgs", "repos_url": "https://api.github.com/users/bpoldrack/repos", "events_url": "https://api.github.com/users/bpoldrack/events{/privacy}", "received_events_url": "https://api.github.com/users/bpoldrack/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "bpoldrack", "id": 10498301, "node_id": "MDQ6VXNlcjEwNDk4MzAx", "avatar_url": "https://avatars.githubusercontent.com/u/10498301?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bpoldrack", "html_url": "https://github.com/bpoldrack", "followers_url": "https://api.github.com/users/bpoldrack/followers", "following_url": "https://api.github.com/users/bpoldrack/following{/other_user}", "gists_url": "https://api.github.com/users/bpoldrack/gists{/gist_id}", "starred_url": "https://api.github.com/users/bpoldrack/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bpoldrack/subscriptions", "organizations_url": "https://api.github.com/users/bpoldrack/orgs", "repos_url": "https://api.github.com/users/bpoldrack/repos", "events_url": "https://api.github.com/users/bpoldrack/events{/privacy}", "received_events_url": "https://api.github.com/users/bpoldrack/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 11, "created_at": "2018-05-24T04:44:59Z", "updated_at": "2018-05-26T14:02:43Z", "closed_at": "2018-05-26T14:02:43Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "It should have \r\n\r\n```\r\nassert_raises(ValueError, clone, 'Zoidberg', path='ssh://mars:Zoidberg')\r\n```\r\n\r\nBut did:\r\n\r\n```\r\n======================================================================\r\n380ERROR: datalad.distribution.tests.test_clone.test_invalid_args\r\n381----------------------------------------------------------------------\r\n382Traceback (most recent call last):\r\n383  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\nose\\case.py\", line 198, in runTest\r\n384    self.test(*self.arg)\r\n385  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 669, in newfunc\r\n386    return t(*(arg + (filename,)), **kw)\r\n387  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\contextlib.py\", line 77, in __exit__\r\n388    self.gen.throw(type, value, traceback)\r\n389  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\utils.py\", line 1307, in make_tempfile\r\n390    yield filename\r\n391  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 669, in newfunc\r\n392    return t(*(arg + (filename,)), **kw)\r\n393  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 669, in newfunc\r\n394    return t(*(arg + (filename,)), **kw)\r\n395  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\contextlib.py\", line 77, in __exit__\r\n396    self.gen.throw(type, value, traceback)\r\n397  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\utils.py\", line 1307, in make_tempfile\r\n398    yield filename\r\n399  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 669, in newfunc\r\n400    return t(*(arg + (filename,)), **kw)\r\n401  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 669, in newfunc\r\n402    return t(*(arg + (filename,)), **kw)\r\n403  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\contextlib.py\", line 77, in __exit__\r\n404    self.gen.throw(type, value, traceback)\r\n405  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\utils.py\", line 1307, in make_tempfile\r\n406    yield filename\r\n407  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 669, in newfunc\r\n408    return t(*(arg + (filename,)), **kw)\r\n409  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\distribution\\tests\\test_clone.py\", line 71, in test_invalid_args\r\n410    assert_raises(ValueError, clone, 'Zoidberg', path='ssh://mars:Zoidberg')\r\n411  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\unittest\\case.py\", line 727, in assertRaises\r\n412    return context.handle('assertRaises', args, kwargs)\r\n413  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\unittest\\case.py\", line 176, in handle\r\n414    callable_obj(*args, **kwargs)\r\n415  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\interface\\utils.py\", line 470, in eval_func\r\n416    return return_func(generator_func)(*args, **kwargs)\r\n417  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\interface\\utils.py\", line 458, in return_func\r\n418    results = list(results)\r\n419  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\interface\\utils.py\", line 446, in generator_func\r\n420    msg=\"Command did not complete successfully\")\r\n421datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'status': 'error', 'type': 'dataset', 'source_url': 'Zoidberg', 'message': ('Failed to clone data from any candidate source URL: %s', ['Zoidberg']), 'action': 'install', 'path': 'C:\\\\projects\\\\datalad-5sgef\\\\__testhome__\\\\ssh:\\\\mars:Zoidberg'}]\r\n```", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/2545/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/2545/timeline", "performed_via_github_app": null}