{"url": "https://api.github.com/repos/datalad/datalad/issues/2689", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/2689/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/2689/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/2689/events", "html_url": "https://github.com/datalad/datalad/issues/2689", "id": 339234442, "node_id": "MDU6SXNzdWUzMzkyMzQ0NDI=", "number": 2689, "title": "2 test failures while building for debian with Python 3.7", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-07-08T15:26:29Z", "updated_at": "2019-07-09T23:57:50Z", "closed_at": "2019-07-09T23:57:49Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "#### What is the problem?\r\nWe need to add 3.7 testing, at least for a single matrix run or may be (also) for appveyor to spread the loa\r\n\r\n```\r\n======================================================================\r\nFAIL: datalad.support.tests.test_network.test_url_samples\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3/dist-packages/nose/case.py\", line 197, in runTest\r\n    self.test(*self.arg)\r\n  File \"/build/datalad-0.10.2/.pybuild/cpython3_3.7_datalad/build/datalad/support/tests/test_network.py\", line 249, in test_url_samples\r\n    _check_ri(\"file:///~/path/sp1\", URL, localpath='/~/path/sp1', scheme='file', path='/~/path/sp1', exact_str=False)\r\n  File \"/build/datalad-0.10.2/.pybuild/cpython3_3.7_datalad/build/datalad/support/tests/test_network.py\", line 139, in _check_ri\r\n    assert_in('Parsed version of', cml.out)\r\nAssertionError: 'Parsed version of' not found in ''\r\n\r\n======================================================================\r\nFAIL: datalad.support.tests.test_network.test_get_local_file_url_linux\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3/dist-packages/nose/case.py\", line 197, in runTest\r\n    self.test(*self.arg)\r\n  File \"/build/datalad-0.10.2/.pybuild/cpython3_3.7_datalad/build/datalad/tests/utils.py\", line 825, in newfunc\r\n    return func(*args, **kwargs)\r\n  File \"/build/datalad-0.10.2/.pybuild/cpython3_3.7_datalad/build/datalad/support/tests/test_network.py\", line 406, in test_get_local_file_url_linux\r\n    eq_(get_local_file_url('/a~'), 'file:///a%7E')\r\nAssertionError: 'file:///a~' != 'file:///a%7E'\r\n```\r\n", "closed_by": {"login": "kyleam", "id": 1297788, "node_id": "MDQ6VXNlcjEyOTc3ODg=", "avatar_url": "https://avatars.githubusercontent.com/u/1297788?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kyleam", "html_url": "https://github.com/kyleam", "followers_url": "https://api.github.com/users/kyleam/followers", "following_url": "https://api.github.com/users/kyleam/following{/other_user}", "gists_url": "https://api.github.com/users/kyleam/gists{/gist_id}", "starred_url": "https://api.github.com/users/kyleam/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kyleam/subscriptions", "organizations_url": "https://api.github.com/users/kyleam/orgs", "repos_url": "https://api.github.com/users/kyleam/repos", "events_url": "https://api.github.com/users/kyleam/events{/privacy}", "received_events_url": "https://api.github.com/users/kyleam/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/2689/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/2689/timeline", "performed_via_github_app": null}