{"url": "https://api.github.com/repos/datalad/datalad/issues/292", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/292/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/292/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/292/events", "html_url": "https://github.com/datalad/datalad/issues/292", "id": 116019618, "node_id": "MDU6SXNzdWUxMTYwMTk2MTg=", "number": 292, "title": "annex_addurl_to_file fails to operate under subdir of the repo", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": {"login": "bpoldrack", "id": 10498301, "node_id": "MDQ6VXNlcjEwNDk4MzAx", "avatar_url": "https://avatars.githubusercontent.com/u/10498301?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bpoldrack", "html_url": "https://github.com/bpoldrack", "followers_url": "https://api.github.com/users/bpoldrack/followers", "following_url": "https://api.github.com/users/bpoldrack/following{/other_user}", "gists_url": "https://api.github.com/users/bpoldrack/gists{/gist_id}", "starred_url": "https://api.github.com/users/bpoldrack/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bpoldrack/subscriptions", "organizations_url": "https://api.github.com/users/bpoldrack/orgs", "repos_url": "https://api.github.com/users/bpoldrack/repos", "events_url": "https://api.github.com/users/bpoldrack/events{/privacy}", "received_events_url": "https://api.github.com/users/bpoldrack/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "bpoldrack", "id": 10498301, "node_id": "MDQ6VXNlcjEwNDk4MzAx", "avatar_url": "https://avatars.githubusercontent.com/u/10498301?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bpoldrack", "html_url": "https://github.com/bpoldrack", "followers_url": "https://api.github.com/users/bpoldrack/followers", "following_url": "https://api.github.com/users/bpoldrack/following{/other_user}", "gists_url": "https://api.github.com/users/bpoldrack/gists{/gist_id}", "starred_url": "https://api.github.com/users/bpoldrack/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bpoldrack/subscriptions", "organizations_url": "https://api.github.com/users/bpoldrack/orgs", "repos_url": "https://api.github.com/users/bpoldrack/repos", "events_url": "https://api.github.com/users/bpoldrack/events{/privacy}", "received_events_url": "https://api.github.com/users/bpoldrack/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 4, "created_at": "2015-11-10T03:47:31Z", "updated_at": "2015-11-12T19:11:56Z", "closed_at": "2015-11-12T19:11:56Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "time to introduce tests for that ;)\n\nannex_addurl_to_file (or to say @normalize_path) resolves name relative to the top dir, not to the current dir (if I give full path or relative -- the same story) to feed them into annex which simply makes it impossible to addurl to a file while under a subdir... or may be I have missed where to fix...\n\nHere is somewhat obscure demo from WiP\n\n```\n$> datalad --dbg add-archive-content -l info svgtune_0.2.0.orig.tar.gz\nGot  svgtune_0.2.0.orig.tar.gz False None None\n2015-11-09 22:33:25,880 [INFO   ] mv /tmp/test-archive-annex/.git/datalad/tmp/archives/dd89b7d50e/svgtune-0.2.0/svgtune svgtune-0.2.0/svgtune. URL: dl+archive:SHA256E-s5121--6d8f7d10206a120a42bec2cd29bc2365d09889fdf070ac8c67d1cff0b1539f63.tar.gz/svgtune-0.2.0/svgtune (add_archive_content.py:172)\n> /home/yoh/proj/datalad/datalad/datalad/interface/add_archive_content.py(178)__call__()\n-> annex.annex_addurl_to_file(target_path, url)\n(Pdb) p target_path\n'/tmp/test-archive-annex/2/3/4/svgtune-0.2.0/svgtune'\n(Pdb) p annex.path\n'/tmp/test-archive-annex'\n(Pdb) curdir()\n*** TypeError: 'str' object is not callable\n(Pdb) getpwd()\n'/tmp/test-archive-annex/2/3/4'\n(Pdb) c\n  while adding a new url to an already annexed file, failed to verify url exists: dl+archive:SHA256E-s5121--6d8f7d10206a120a42bec2cd29bc2365d09889fdf070ac8c67d1cff0b1539f63.tar.gz/svgtune-0.2.0/svgtune\ngit-annex: addurl: 1 failed\n2015-11-09 22:34:19,861 [ERROR  ] Failed to run ['git-annex', 'addurl', '--file=2/3/4/svgtune-0.2.0/svgtune', 'dl+archive:SHA256E-s5121--6d8f7d10206a120a42bec2cd29bc2365d09889fdf070ac8c67d1cff0b1539f63.tar.gz/svgtune-0.2.0/svgtune'] under '/tmp/test-archive-annex'. Exit code=1. out=addurl 2/3/4/svgtune-0.2.0/svgtune \n| failed\n|  err= (cmd.py:269)\nTraceback (most recent call last):\n  File \"/home/yoh/proj/datalad/datalad/venv-tests/bin/datalad\", line 9, in <module>\n    load_entry_point('datalad==0.1.dev0', 'console_scripts', 'datalad')()\n  File \"/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py\", line 199, in main\n    cmdlineargs.func(cmdlineargs)\n  File \"/home/yoh/proj/datalad/datalad/datalad/interface/base.py\", line 146, in call_from_parser\n    return self(**kwargs)\n  File \"/home/yoh/proj/datalad/datalad/datalad/interface/add_archive_content.py\", line 178, in __call__\n    annex.annex_addurl_to_file(target_path, url)\n  File \"/home/yoh/proj/datalad/datalad/datalad/support/gitrepo.py\", line 116, in newfunc\n    return func(self, file_new, *args, **kwargs)\n  File \"/home/yoh/proj/datalad/datalad/datalad/support/annexrepo.py\", line 515, in annex_addurl_to_file\n    log_stderr=False)\n  File \"/home/yoh/proj/datalad/datalad/datalad/support/annexrepo.py\", line 227, in _run_annex_command\n    raise e\nCommandError: CommandError: command '['git-annex', 'addurl', '--file=2/3/4/svgtune-0.2.0/svgtune', 'dl+archive:SHA256E-s5121--6d8f7d10206a120a42bec2cd29bc2365d09889fdf070ac8c67d1cff0b1539f63.tar.gz/svgtune-0.2.0/svgtune']' failed with exitcode 1.\nFailed to run ['git-annex', 'addurl', '--file=2/3/4/svgtune-0.2.0/svgtune', 'dl+archive:SHA256E-s5121--6d8f7d10206a120a42bec2cd29bc2365d09889fdf070ac8c67d1cff0b1539f63.tar.gz/svgtune-0.2.0/svgtune'] under '/tmp/test-archive-annex'. Exit code=1. out=addurl 2/3/4/svgtune-0.2.0/svgtune \nfailed\n err=\n()\n> /home/yoh/proj/datalad/datalad/datalad/support/annexrepo.py(227)_run_annex_command()\n-> raise e\n```\n\nP.S. I see lots of new getcwd used -- better to use getpwd introduced in f2f9ab0b5b994dfd3b74975a8bf5e303550346bd  so we could reliably chdir if needed and go back.  see that commit comment on reasoning\n", "closed_by": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/292/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/292/timeline", "performed_via_github_app": null}