{"url": "https://api.github.com/repos/datalad/datalad/issues/3130", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/3130/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/3130/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/3130/events", "html_url": "https://github.com/datalad/datalad/issues/3130", "id": 404057640, "node_id": "MDU6SXNzdWU0MDQwNTc2NDA=", "number": 3130, "title": "appveyor became unhappy (recent annex release?)", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 188141023, "node_id": "MDU6TGFiZWwxODgxNDEwMjM=", "url": "https://api.github.com/repos/datalad/datalad/labels/platform-windows", "name": "platform-windows", "color": "0052cc", "default": false, "description": "Issue concerned with Windows"}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 11, "created_at": "2019-01-28T23:44:43Z", "updated_at": "2019-02-20T04:20:19Z", "closed_at": "2019-02-20T04:20:19Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "initially ran into in https://github.com/datalad/datalad/pull/3129\r\n\r\nI think it is due to new annex cmd:annex: 7.20190122-gc94b3a389  since a few days prior that tests were all green.\r\nfailure\r\n```\r\n======================================================================\r\nFAIL: datalad.distribution.tests.test_install.test_datasets_datalad_org('',)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\nose\\case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 849, in newfunc\r\n    return func(*args, **kwargs)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 615, in newfunc\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\distribution\\tests\\test_install.py\", line 945, in check_datasets_datalad_org\r\n    status='ok')\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 1281, in assert_result_count\r\n    dumps(results, indent=1, default=lambda x: str(x))))\r\nAssertionError: Got 0 instead of 1 expected results matching {'status': 'ok'}. Inspected 1 record(s):\r\n[\r\n {\r\n  \"status\": \"notneeded\",\r\n  \"path\": \"C:\\\\Users\\\\appveyor\\\\AppData\\\\Local\\\\Temp\\\\1\\\\datalad_temp_81qc9hhh\\\\001-anat-scout_ses-{date}\\\\000001.dcm\",\r\n  \"type\": \"file\",\r\n  \"refds\": \"C:\\\\Users\\\\appveyor\\\\AppData\\\\Local\\\\Temp\\\\1\\\\datalad_temp_81qc9hhh\",\r\n  \"action\": \"get\",\r\n  \"message\": \"already present\"\r\n }\r\n]\r\n======================================================================\r\nFAIL: datalad.distribution.tests.test_install.test_datasets_datalad_org('/.git',)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\nose\\case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 849, in newfunc\r\n    return func(*args, **kwargs)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 615, in newfunc\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\distribution\\tests\\test_install.py\", line 945, in check_datasets_datalad_org\r\n    status='ok')\r\n  File \"C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\utils.py\", line 1281, in assert_result_count\r\n    dumps(results, indent=1, default=lambda x: str(x))))\r\nAssertionError: Got 0 instead of 1 expected results matching {'status': 'ok'}. Inspected 1 record(s):\r\n[\r\n {\r\n  \"status\": \"notneeded\",\r\n  \"path\": \"C:\\\\Users\\\\appveyor\\\\AppData\\\\Local\\\\Temp\\\\1\\\\datalad_temp_fi91roug\\\\001-anat-scout_ses-{date}\\\\000001.dcm\",\r\n  \"type\": \"file\",\r\n  \"refds\": \"C:\\\\Users\\\\appveyor\\\\AppData\\\\Local\\\\Temp\\\\1\\\\datalad_temp_fi91roug\",\r\n  \"action\": \"get\",\r\n  \"message\": \"already present\"\r\n }\r\n]\r\n```", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/3130/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/3130/timeline", "performed_via_github_app": null}