{"url": "https://api.github.com/repos/datalad/datalad/issues/3432", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/3432/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/3432/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/3432/events", "html_url": "https://github.com/datalad/datalad/issues/3432", "id": 445627660, "node_id": "MDU6SXNzdWU0NDU2Mjc2NjA=", "number": 3432, "title": "testing against datalad-neuroimaging started to fail", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 440544386, "node_id": "MDU6TGFiZWw0NDA1NDQzODY=", "url": "https://api.github.com/repos/datalad/datalad/labels/fix-implemented", "name": "fix-implemented", "color": "0e8a16", "default": false, "description": "A fix is available, but has not been merged or released, yet."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2019-05-17T21:39:09Z", "updated_at": "2019-05-20T15:04:03Z", "closed_at": "2019-05-20T15:04:03Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "either due to datalad-neuroimaging release or some changes here (happens for PRs against 0.11.x) and I failed so far to reproduce locally (python2)\r\n```\r\n38.26s$ http_proxy= PATH=$PWD/../tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -A \"$NOSE_SELECTION_OP($NOSE_SELECTION)\" --with-doctest --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM\r\n.........SS.E.S.\r\n======================================================================\r\nERROR: datalad_neuroimaging.tests.test_procedure.test_bids_procedure\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py\", line 615, in newfunc\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad_neuroimaging/tests/test_procedure.py\", line 13, in test_bids_procedure\r\n    ds.run_procedure(['cfg_bids'])\r\n  File \"/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/distribution/dataset.py\", line 526, in apply_func\r\n    return f(**kwargs)\r\n  File \"/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/interface/utils.py\", line 492, in eval_func\r\n    return return_func(generator_func)(*args, **kwargs)\r\n  File \"/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/interface/utils.py\", line 480, in return_func\r\n    results = list(results)\r\n  File \"/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/interface/utils.py\", line 468, in generator_func\r\n    msg=\"Command did not complete successfully\")\r\ndatalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'action': 'run_procedure', 'status': 'impossible', 'refds': '/tmp/datalad_temp_test_bids_procedure0ucvyzgv', 'path': 'cfg_bids', 'message': \"Cannot find procedure with name 'cfg_bids'\"}]\r\n```", "closed_by": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/3432/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/3432/timeline", "performed_via_github_app": null}