{"url": "https://api.github.com/repos/datalad/datalad/issues/3968", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/3968/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/3968/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/3968/events", "html_url": "https://github.com/datalad/datalad/issues/3968", "id": 543073570, "node_id": "MDU6SXNzdWU1NDMwNzM1NzA=", "number": 3968, "title": "Minor issue: datalad get would fail for newly pulled subdatasets", "user": {"login": "dorianps", "id": 9083517, "node_id": "MDQ6VXNlcjkwODM1MTc=", "avatar_url": "https://avatars.githubusercontent.com/u/9083517?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dorianps", "html_url": "https://github.com/dorianps", "followers_url": "https://api.github.com/users/dorianps/followers", "following_url": "https://api.github.com/users/dorianps/following{/other_user}", "gists_url": "https://api.github.com/users/dorianps/gists{/gist_id}", "starred_url": "https://api.github.com/users/dorianps/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dorianps/subscriptions", "organizations_url": "https://api.github.com/users/dorianps/orgs", "repos_url": "https://api.github.com/users/dorianps/repos", "events_url": "https://api.github.com/users/dorianps/events{/privacy}", "received_events_url": "https://api.github.com/users/dorianps/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2019-12-28T05:57:13Z", "updated_at": "2020-01-10T14:54:07Z", "closed_at": "2020-01-10T14:54:07Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### What is the problem?\r\nSuppose there two clones of a datalad superdataset in A and B, both having the subdatasets 1,2,3. If B adds a new subdataset 4, and A adds B's location as a sibling and runs `datalad update --merge --sibling B`, what happens is that A will now have subdataset 4, but cannot get the actual data. To get the data you normally run `datalad get --source B`, but this would fail because the new subdataset 4 does not have B as a remote in A. The workaround is to add manually the remote B on the newly pulled subdataset 4 inside A, then try `get` again. \r\n\r\n#### What steps will reproduce the problem?\r\nSorry, no code for now, above explanation should help create the situation.\r\n\r\n#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?\r\n0.12.0rc6 from Github on Dec 2019\r\n\r\n#### Is there anything else that would be useful to know in this context?\r\nThough this is not a serious bug, it is confusing to the user. Moreover, it is problematic when there are hundreds of subdatasets. Running `sibling add` one by one is not reasonable, so I usually go for `sibling add --recursive` from the parent dataset. This in turn throws lots of errors for existing remotes in old subdatasets, but fixes the new ones too. The point is that the process is not smooth and shows errors. Maybe datalad can handle this situation automatically.\r\n\r\n#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)\r\nNA\r\n", "closed_by": {"login": "kyleam", "id": 1297788, "node_id": "MDQ6VXNlcjEyOTc3ODg=", "avatar_url": "https://avatars.githubusercontent.com/u/1297788?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kyleam", "html_url": "https://github.com/kyleam", "followers_url": "https://api.github.com/users/kyleam/followers", "following_url": "https://api.github.com/users/kyleam/following{/other_user}", "gists_url": "https://api.github.com/users/kyleam/gists{/gist_id}", "starred_url": "https://api.github.com/users/kyleam/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kyleam/subscriptions", "organizations_url": "https://api.github.com/users/kyleam/orgs", "repos_url": "https://api.github.com/users/kyleam/repos", "events_url": "https://api.github.com/users/kyleam/events{/privacy}", "received_events_url": "https://api.github.com/users/kyleam/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/3968/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/3968/timeline", "performed_via_github_app": null}