{"url": "https://api.github.com/repos/datalad/datalad/issues/4300", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/4300/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/4300/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/4300/events", "html_url": "https://github.com/datalad/datalad/issues/4300", "id": 581183463, "node_id": "MDU6SXNzdWU1ODExODM0NjM=", "number": 4300, "title": "FAIL: datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed", "user": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 63778590, "node_id": "MDU6TGFiZWw2Mzc3ODU5MA==", "url": "https://api.github.com/repos/datalad/datalad/labels/severity-normal", "name": "severity-normal", "color": "ff8888", "default": false, "description": "standard severity"}, {"id": 188141023, "node_id": "MDU6TGFiZWwxODgxNDEwMjM=", "url": "https://api.github.com/repos/datalad/datalad/labels/platform-windows", "name": "platform-windows", "color": "0052cc", "default": false, "description": "Issue concerned with Windows"}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-03-14T12:14:48Z", "updated_at": "2020-03-15T08:27:49Z", "closed_at": "2020-03-15T08:27:49Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "```\r\n======================================================================\r\nFAIL: datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(True,)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\mih\\Miniconda3\\lib\\site-packages\\nose\\case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\tests\\utils.py\", line 518, in newfunc\r\n    return t(*(arg + (d,)), **kw)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\support\\tests\\test_annexrepo.py\", line 2174, in check_commit_annex_commit_changed\r\n    assert_repo_status(path)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\tests\\utils.py\", line 1575, in assert_repo_status\r\n    % (state, state_files, oktobefound))\r\nAssertionError: unexpected content of state \"modified\": [WindowsPath('C:/Users/mih/AppData/Local/Temp/datalad_temp_tree_7gtel35p/.gitattributes')] != []\r\n-------------------- >> begin captured logging << --------------------\r\nasyncio: DEBUG: Using proactor: IocpProactor\r\n--------------------- >> end captured logging << ---------------------\r\n\r\n======================================================================\r\nFAIL: datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(False,)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\mih\\Miniconda3\\lib\\site-packages\\nose\\case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\tests\\utils.py\", line 518, in newfunc\r\n    return t(*(arg + (d,)), **kw)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\support\\tests\\test_annexrepo.py\", line 2174, in check_commit_annex_commit_changed\r\n    assert_repo_status(path)\r\n  File \"C:\\Users\\mih\\code\\datalad\\datalad\\tests\\utils.py\", line 1575, in assert_repo_status\r\n    % (state, state_files, oktobefound))\r\nAssertionError: unexpected content of state \"modified\": [WindowsPath('C:/Users/mih/AppData/Local/Temp/datalad_temp_tree_ofl91kvh/.gitattributes')] != []\r\n```", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/4300/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/4300/timeline", "performed_via_github_app": null}