{"url": "https://api.github.com/repos/datalad/datalad/issues/4773", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/4773/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/4773/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/4773/events", "html_url": "https://github.com/datalad/datalad/issues/4773", "id": 666593565, "node_id": "MDU6SXNzdWU2NjY1OTM1NjU=", "number": 4773, "title": "test_AnnexRepo_commit failures on Travis", "user": {"login": "kyleam", "id": 1297788, "node_id": "MDQ6VXNlcjEyOTc3ODg=", "avatar_url": "https://avatars.githubusercontent.com/u/1297788?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kyleam", "html_url": "https://github.com/kyleam", "followers_url": "https://api.github.com/users/kyleam/followers", "following_url": "https://api.github.com/users/kyleam/following{/other_user}", "gists_url": "https://api.github.com/users/kyleam/gists{/gist_id}", "starred_url": "https://api.github.com/users/kyleam/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kyleam/subscriptions", "organizations_url": "https://api.github.com/users/kyleam/orgs", "repos_url": "https://api.github.com/users/kyleam/repos", "events_url": "https://api.github.com/users/kyleam/events{/privacy}", "received_events_url": "https://api.github.com/users/kyleam/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 884298512, "node_id": "MDU6TGFiZWw4ODQyOTg1MTI=", "url": "https://api.github.com/repos/datalad/datalad/labels/fails-on-travis", "name": "fails-on-travis", "color": "eda19a", "default": false, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 11, "created_at": "2020-07-27T21:23:00Z", "updated_at": "2020-08-27T07:06:38Z", "closed_at": "2020-08-27T07:06:38Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "`test_AnnexRepo_commit` failed in two recent PRs (gh-4762 and gh-4768).  I think it's intermittent.\r\n\r\n- https://travis-ci.org/github/datalad/datalad/jobs/712219198#L1996\r\n- https://travis-ci.org/github/datalad/datalad/jobs/712340298#L1991\r\n\r\n```\r\n======================================================================\r\nERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_commit\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/tests/utils.py\", line 1185, in newfunc\r\n    raise exc_info[1]\r\n  File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/tests/utils.py\", line 1157, in newfunc\r\n    ret = func(*args, **kwargs)\r\n  File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/tests/utils.py\", line 728, in newfunc\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/support/tests/test_annexrepo.py\", line 786, in test_AnnexRepo_commit\r\n    assert_raises(FileNotInRepositoryError, ds.commit, files=\"not-existing\")\r\n  File \"/opt/python/3.7.1/lib/python3.7/unittest/case.py\", line 743, in assertRaises\r\n    return context.handle('assertRaises', args, kwargs)\r\n  File \"/opt/python/3.7.1/lib/python3.7/unittest/case.py\", line 178, in handle\r\n    callable_obj(*args, **kwargs)\r\n  File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/support/gitrepo.py\", line 1654, in commit\r\n    stdin=None,\r\n  File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/cmd.py\", line 504, in run\r\n    **results,\r\ndatalad.support.exceptions.CommandError: CommandError: 'git commit -m '[DATALAD] Recorded changes' -- not-existing' failed with exitcode 1 under /tmp/datalad_temp_test_AnnexRepo_commitmkv02v44\r\n```", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/4773/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/4773/timeline", "performed_via_github_app": null}