{"url": "https://api.github.com/repos/datalad/datalad/issues/4897", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/4897/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/4897/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/4897/events", "html_url": "https://github.com/datalad/datalad/pull/4897", "id": 694971257, "node_id": "MDExOlB1bGxSZXF1ZXN0NDgxMjc2ODE1", "number": 4897, "title": "TST: Refcount is unreliable ATM", "user": {"login": "bpoldrack", "id": 10498301, "node_id": "MDQ6VXNlcjEwNDk4MzAx", "avatar_url": "https://avatars.githubusercontent.com/u/10498301?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bpoldrack", "html_url": "https://github.com/bpoldrack", "followers_url": "https://api.github.com/users/bpoldrack/followers", "following_url": "https://api.github.com/users/bpoldrack/following{/other_user}", "gists_url": "https://api.github.com/users/bpoldrack/gists{/gist_id}", "starred_url": "https://api.github.com/users/bpoldrack/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bpoldrack/subscriptions", "organizations_url": "https://api.github.com/users/bpoldrack/orgs", "repos_url": "https://api.github.com/users/bpoldrack/repos", "events_url": "https://api.github.com/users/bpoldrack/events{/privacy}", "received_events_url": "https://api.github.com/users/bpoldrack/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2020-09-07T10:43:45Z", "updated_at": "2020-09-08T07:27:05Z", "closed_at": "2020-09-08T07:27:01Z", "author_association": "MEMBER", "active_lock_reason": null, "pull_request": {"url": "https://api.github.com/repos/datalad/datalad/pulls/4897", "html_url": "https://github.com/datalad/datalad/pull/4897", "diff_url": "https://github.com/datalad/datalad/pull/4897.diff", "patch_url": "https://github.com/datalad/datalad/pull/4897.patch"}, "body": "In light of (unresolved) issue #4862, it seems necessary to adapt the tests for now.\r\nSince the issue is neither happening for me locally nor on Travis, I need you, @kyleam and @mih to confirm, that these tests are passing for you with this patch.\r\n\r\nIf so, I'll need to dig out #4849 in addition (and find a better solution for that one).", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/4897/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/4897/timeline", "performed_via_github_app": null}