{"url": "https://api.github.com/repos/datalad/datalad/issues/4958", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/4958/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/4958/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/4958/events", "html_url": "https://github.com/datalad/datalad/issues/4958", "id": 708263815, "node_id": "MDU6SXNzdWU3MDgyNjM4MTU=", "number": 4958, "title": "maint: failing test  test_ExtractedArchive on maint on NFS", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-09-24T15:21:43Z", "updated_at": "2021-03-04T22:40:47Z", "closed_at": "2021-03-04T22:40:47Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "eh heh -- merging of https://github.com/datalad/datalad/pull/4931 (before merging #4953 but after #4949 for which it was green) triggered test failure under NFS:\r\nhttps://travis-ci.org/github/datalad/datalad/jobs/729943926\r\n```\r\n======================================================================\r\nFAIL: datalad.tests.test_archives.test_ExtractedArchive\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py\", line 554, in _wrap_with_tree\r\n    return t(*(arg + (d,)), **kw)\r\n  File \"/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/test_archives.py\", line 202, in test_ExtractedArchive\r\n    op.join(fn_archive_obscure, '3.txt')\r\nAssertionError: [' b|;& \u0394\u0419\u05e7\u0645\u0e57\u3042.dbtc / a|;& \u0394\u0419\u05e7\u0645\u0e57\u3042.datc '] != [' b|;& \u0394\u0419\u05e7\u0645\u0e57\u3042.dbtc / a|;& \u0394\u0419\u05e7\u0645\u0e57\u3042.datc ', ' b|;& \u0394\u0419\u05e7\u0645\u0e57\u3042.dbtc /3.txt']\r\n```\r\nwhen ran in the `maint` branch on `DATALAD_TESTS_SSH=0 _DL_TMPDIR=\"/tmp/nfsmount\" TESTS_TO_PERFORM=\"datalad.tests datalad.support\"` matrix run. \r\n\r\nLet's see if current build after merging #4953 \"fixes it\"... but I just wanted to make a note since may be some flaky test somehow", "closed_by": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/4958/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/4958/timeline", "performed_via_github_app": null}