{"url": "https://api.github.com/repos/datalad/datalad/issues/5298", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/5298/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/5298/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/5298/events", "html_url": "https://github.com/datalad/datalad/issues/5298", "id": 781934065, "node_id": "MDU6SXNzdWU3ODE5MzQwNjU=", "number": 5298, "title": "FAIL: datalad.distribution.tests.test_create_sibling.test_target_ssh_simple", "user": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 63778590, "node_id": "MDU6TGFiZWw2Mzc3ODU5MA==", "url": "https://api.github.com/repos/datalad/datalad/labels/severity-normal", "name": "severity-normal", "color": "ff8888", "default": false, "description": "standard severity"}, {"id": 440544386, "node_id": "MDU6TGFiZWw0NDA1NDQzODY=", "url": "https://api.github.com/repos/datalad/datalad/labels/fix-implemented", "name": "fix-implemented", "color": "0e8a16", "default": false, "description": "A fix is available, but has not been merged or released, yet."}, {"id": 1431258059, "node_id": "MDU6TGFiZWwxNDMxMjU4MDU5", "url": "https://api.github.com/repos/datalad/datalad/labels/fails-on-appveyor", "name": "fails-on-appveyor", "color": "eda19a", "default": false, "description": ""}, {"id": 2641486155, "node_id": "MDU6TGFiZWwyNjQxNDg2MTU1", "url": "https://api.github.com/repos/datalad/datalad/labels/platform-linux", "name": "platform-linux", "color": "0052cc", "default": false, "description": "Issues concerned with Linux"}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2021-01-08T08:10:06Z", "updated_at": "2021-03-09T08:15:58Z", "closed_at": "2021-03-09T08:15:58Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "```\r\nTraceback (most recent call last):\r\n1506  File \"/home/appveyor/dlvenv/lib/python3.8/site-packages/nose/case.py\", line 198, in runTest\r\n1507    self.test(*self.arg)\r\n1508  File \"/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py\", line 206, in _wrap_skip_if_on_windows\r\n1509    return func(*args, **kwargs)\r\n1510  File \"/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py\", line 291, in _wrap_skip_ssh\r\n1511    return func(*args, **kwargs)\r\n1512  File \"/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py\", line 1103, in _wrap_with_testrepos\r\n1513    t(*(arg + (uri,)), **kw)\r\n1514  File \"/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py\", line 772, in _wrap_with_tempfile\r\n1515    return t(*(arg + (filename,)), **kw)\r\n1516  File \"/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py\", line 772, in _wrap_with_tempfile\r\n1517    return t(*(arg + (filename,)), **kw)\r\n1518  File \"/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/distribution/tests/test_create_sibling.py\", line 332, in test_target_ssh_simple\r\n1519    assert_dict_equal(orig_digests, digests)  # nothing should change in terms of content\r\n1520  File \"/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py\", line 1375, in assert_dict_equal\r\n1521    raise AssertionError(\"dicts differ:\\n%s\" % \"\\n\".join(msgs))\r\n1522AssertionError: dicts differ:\r\n1523 ['.git/logs/HEAD'] differs: {'md5': '0bf92a551cc258c32cf21f784beaf7f2'} != {'md5': '3cc84ba60fc9b7d1d550c5bc89f314ba'}\r\n```\r\n\r\nhttps://ci.appveyor.com/project/mih/appveyor-datalad/build/job/cq8t16bcpw02lw4d", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/5298/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/5298/timeline", "performed_via_github_app": null}