{"url": "https://api.github.com/repos/datalad/datalad/issues/5318", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/5318/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/5318/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/5318/events", "html_url": "https://github.com/datalad/datalad/issues/5318", "id": 784285429, "node_id": "MDU6SXNzdWU3ODQyODU0Mjk=", "number": 5318, "title": "change in git-annex behavior:  --trust option no longer overrides trust", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 440544386, "node_id": "MDU6TGFiZWw0NDA1NDQzODY=", "url": "https://api.github.com/repos/datalad/datalad/labels/fix-implemented", "name": "fix-implemented", "color": "0e8a16", "default": false, "description": "A fix is available, but has not been merged or released, yet."}, {"id": 1782622781, "node_id": "MDU6TGFiZWwxNzgyNjIyNzgx", "url": "https://api.github.com/repos/datalad/datalad/labels/severity-important", "name": "severity-important", "color": "cc0000", "default": false, "description": "major effect on the usability of a package, without rendering it completely unusable to everyone"}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2021-01-12T14:27:22Z", "updated_at": "2021-01-12T19:23:03Z", "closed_at": "2021-01-12T19:23:03Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "```\r\n======================================================================\r\nERROR: datalad.distributed.tests.test_create_sibling_ria.test_create_simple(None,)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py\", line 197, in _wrap_skip_if_on_windows\r\n    return func(*args, **kwargs)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py\", line 750, in _wrap_with_tempfile\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/distributed/tests/test_create_sibling_ria.py\", line 49, in _wrap_with_store_insteadof\r\n    return func(*args, **kwargs)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py\", line 573, in _wrap_with_tree\r\n    return t(*(arg + (d,)), **kw)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py\", line 750, in _wrap_with_tempfile\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/distributed/tests/test_create_sibling_ria.py\", line 162, in _test_create_store\r\n    trust_level=trust)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/distribution/dataset.py\", line 503, in apply_func\r\n    return f(**kwargs)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/interface/utils.py\", line 495, in eval_func\r\n    return return_func(generator_func)(*args, **kwargs)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/interface/utils.py\", line 483, in return_func\r\n    results = list(results)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/interface/utils.py\", line 414, in generator_func\r\n    allkwargs):\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/interface/utils.py\", line 570, in _process_results\r\n    for res in results:\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/distributed/create_sibling_ria.py\", line 356, in __call__\r\n    res_kwargs)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/distributed/create_sibling_ria.py\", line 532, in _create_sibling_ria\r\n    ds.repo.call_git(['annex', trust_level, storage_name])\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/support/gitrepo.py\", line 2133, in call_git\r\n    check_fake_dates=True)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/support/gitrepo.py\", line 329, in _wrap_normalize_paths\r\n    result = func(self, files_new, *args, **kwargs)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/support/gitrepo.py\", line 2084, in _git_custom_command\r\n    expect_fail=expect_fail)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/cmd.py\", line 144, in run_gitcommand_on_file_list_chunks\r\n    results.append(func(cmd, *args, **kwargs))\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/cmd.py\", line 1155, in run\r\n    *args, **kwargs)\r\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/cmd.py\", line 966, in run\r\n    raise exc\r\ndatalad.support.exceptions.CommandError: CommandError: 'git annex trust datastore-storage' failed with exitcode 1 under /tmp/datalad_temp_tree__test_create_store5iiehbh8 [out: 'trust datastore-storage \r\nfailed'] [err: 'git-annex: Trusting a repository can lead to data loss. If you're sure you know what you're doing, use --force to make this take effect. If you choose to do so, bear in mind that any time you drop content from datastore-storage, you will risk losing data.\r\ngit-annex: trust: 1 failed']\r\n```\r\nIt is a very recent change and likely the result of  [8.20201129-74-g2bf34fc17](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=2bf34fc17f081618f07e33a8e7ff633906962bc3)\r\n\r\n```\r\n  commit 2bf34fc17f081618f07e33a8e7ff633906962bc3\r\n  Author: Joey Hess <id@joeyh.name>\r\n  Date:   Thu Jan 7 10:12:37 2021 -0400\r\n  \r\n      Behavior change: --trust option no longer overrides trust\r\n      \r\n      Since that can lead to data loss, which should never be enabled by an\r\n      option other than --force.\r\n      \r\n      I suppose that using --trust was in some situation, safer than --force,\r\n```\r\nand that affects all versions (released and not) testing :-/", "closed_by": {"login": "kyleam", "id": 1297788, "node_id": "MDQ6VXNlcjEyOTc3ODg=", "avatar_url": "https://avatars.githubusercontent.com/u/1297788?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kyleam", "html_url": "https://github.com/kyleam", "followers_url": "https://api.github.com/users/kyleam/followers", "following_url": "https://api.github.com/users/kyleam/following{/other_user}", "gists_url": "https://api.github.com/users/kyleam/gists{/gist_id}", "starred_url": "https://api.github.com/users/kyleam/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kyleam/subscriptions", "organizations_url": "https://api.github.com/users/kyleam/orgs", "repos_url": "https://api.github.com/users/kyleam/repos", "events_url": "https://api.github.com/users/kyleam/events{/privacy}", "received_events_url": "https://api.github.com/users/kyleam/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/5318/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/5318/timeline", "performed_via_github_app": null}