{"url": "https://api.github.com/repos/datalad/datalad/issues/5482", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/5482/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/5482/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/5482/events", "html_url": "https://github.com/datalad/datalad/issues/5482", "id": 828181506, "node_id": "MDU6SXNzdWU4MjgxODE1MDY=", "number": 5482, "title": "Call to datalad.api.save() stall forever in a Django app", "user": {"login": "20", "id": 921216, "node_id": "MDQ6VXNlcjkyMTIxNg==", "avatar_url": "https://avatars.githubusercontent.com/u/921216?v=4", "gravatar_id": "", "url": "https://api.github.com/users/20", "html_url": "https://github.com/20", "followers_url": "https://api.github.com/users/20/followers", "following_url": "https://api.github.com/users/20/following{/other_user}", "gists_url": "https://api.github.com/users/20/gists{/gist_id}", "starred_url": "https://api.github.com/users/20/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/20/subscriptions", "organizations_url": "https://api.github.com/users/20/orgs", "repos_url": "https://api.github.com/users/20/repos", "events_url": "https://api.github.com/users/20/events{/privacy}", "received_events_url": "https://api.github.com/users/20/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2021-03-10T18:43:11Z", "updated_at": "2021-03-11T13:57:35Z", "closed_at": "2021-03-11T13:57:34Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### What is the problem?\r\nCall to datalad.api.save() stall forever\r\nI'm using python datalad.api in a simple new django (3.1) app .. When I call save() the process stall..\r\nTrying to debug I saw that git process dies while reading buffer.  \r\nIf I try saving the same dataset using same repository with bash shell and ipython, it works normally.\r\n\r\n#### What steps will reproduce the problem?\r\n\r\n```python\r\nfrom datalad.api import Dataset\r\nimport pdb\r\nfrom datalad import lgr\r\n\r\nfrom . import utils\r\n\r\nfrom django.utils.translation import ugettext_lazy as _\r\n\r\nimport os\r\nimport shutil\r\nimport logging \r\n\r\nlogger = logging.getLogger(__name__)\r\n\r\ndef dataset_update(content):\r\n    try:\r\n        content_new_path = utils.get_content_path(content)\r\n        os.makedirs(os.path.dirname(content_new_path), exist_ok=True)\r\n        shutil.move(content.artefact.path, os.path.join(\r\n                content_new_path, content.get_human_id))\r\n    except Exception as e:\r\n        logger.info(_(\"Something wrong during file move execution: \"\r\n                      + e.__doc__))        \r\n    try:\r\n        lgr.setLevel(2)\r\n        pdb.set_trace()\r\n        ds = Dataset(path=content.repository.path)    \r\n        os.environ['GIT_COMMITTER_NAME'] = content.mocambola.username\r\n        os.environ['GIT_COMMITTER_EMAIL'] = content.mocambola.email\r\n        logger.info(os.environ['GIT_COMMITTER_NAME']+'and'+os.environ['GIT_COMMITTER_EMAIL'])\r\n        ds.save()\r\n    except Exception as e:\r\n        logger.info(_(\"Something happened during datalad execution: \"\r\n                      + e.__doc__))   \r\n```\r\n\r\n**Full code and installation:**\r\n- git clone https://labmocambos.taina.net.br/npdd/baobaxiaa\r\n- cd baobaxiaa/baobaxia\r\n- docker-compose up --build\r\n- docker exec -it baobaxiaa_baobaxia_1 /bin/bash python3 manage.py loaddata apps/bbx/fixtures/dados_iniciais.json\r\n- You can login in django admin with user:livre pass:livre \r\n- Uncomment call to dataset_update() on baobaxia/apps/bbx/models.py at the end of BaseContent save()\r\n\r\n#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?\r\n\r\n<details>\r\n<summary>datalad wtf -D html_details</summary> \r\n\r\nDataLad 0.14.0 WTF (configuration, credentials, datalad, dataset, dependencies, environment, extensions, git-annex, location, metadata_extractors, metadata_indexers, python, system)</summary>\r\n\r\n# WTF\r\n## configuration <SENSITIVE, report disabled by configuration>\r\n## credentials \r\n  - keyring: \r\n    - active_backends: \r\n      - SecretService Keyring\r\n      - EncryptedKeyring with [PBKDF2] AES256.CFB v.1.0 at /home/befree/.local/share/python_keyring/crypted_pass.cfg\r\n      - PlaintextKeyring with no encyption v.1.0 at /home/befree/.local/share/python_keyring/keyring_pass.cfg\r\n    - config_file: /home/befree/.local/share/python_keyring/keyringrc.cfg\r\n    - data_root: /home/befree/.local/share/python_keyring\r\n## datalad \r\n  - full_version: 0.14.0\r\n  - version: 0.14.0\r\n## dataset \r\n  - id: c936b3b0-1a66-478e-be8f-81440bd7a22d\r\n  - metadata: <SENSITIVE, report disabled by configuration>\r\n  - path: /data/bbx/repositories/rede-mocambos-123456\r\n  - repo: AnnexRepo\r\n## dependencies \r\n  - annexremote: 1.4.3\r\n  - appdirs: 1.4.3\r\n  - boto: 2.44.0\r\n  - cmd:7z: 16.02\r\n  - cmd:annex: 7.20190819+git2-g908476a9b-1~ndall+1\r\n  - cmd:bundled-git: 2.20.1\r\n  - cmd:git: 2.20.1\r\n  - cmd:system-git: 2.24.0\r\n  - cmd:system-ssh: 7.9p1\r\n  - exifread: 2.1.2\r\n  - humanize: 0.5.1\r\n  - iso8601: 0.1.11\r\n  - keyring: 17.1.1\r\n  - keyrings.alt: 3.1.1\r\n  - msgpack: 0.5.6\r\n  - mutagen: 1.40.0\r\n  - requests: 2.21.0\r\n  - wrapt: 1.10.11\r\n## environment \r\n  - LANG: it_IT.UTF-8\r\n  - PATH: /home/befree/.yarn/bin:/home/befree/.config/yarn/global/node_modules/.bin:/home/befree/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/sbin\r\n## extensions \r\n## git-annex \r\n  - build flags: \r\n    - Assistant\r\n    - Webapp\r\n    - Pairing\r\n    - S3\r\n    - WebDAV\r\n    - Inotify\r\n    - DBus\r\n    - DesktopNotify\r\n    - TorrentParser\r\n    - MagicMime\r\n    - Feeds\r\n    - Testsuite\r\n  - dependency versions: \r\n    - aws-0.20\r\n    - bloomfilter-2.0.1.0\r\n    - cryptonite-0.25\r\n    - DAV-1.3.3\r\n    - feed-1.0.0.0\r\n    - ghc-8.4.4\r\n    - http-client-0.5.13.1\r\n    - persistent-sqlite-2.8.2\r\n    - torrent-10000.1.1\r\n    - uuid-1.3.13\r\n    - yesod-1.6.0\r\n  - key/value backends: \r\n    - SHA256E\r\n    - SHA256\r\n    - SHA512E\r\n    - SHA512\r\n    - SHA224E\r\n    - SHA224\r\n    - SHA384E\r\n    - SHA384\r\n    - SHA3_256E\r\n    - SHA3_256\r\n    - SHA3_512E\r\n    - SHA3_512\r\n    - SHA3_224E\r\n    - SHA3_224\r\n    - SHA3_384E\r\n    - SHA3_384\r\n    - SKEIN256E\r\n    - SKEIN256\r\n    - SKEIN512E\r\n    - SKEIN512\r\n    - BLAKE2B256E\r\n    - BLAKE2B256\r\n    - BLAKE2B512E\r\n    - BLAKE2B512\r\n    - BLAKE2B160E\r\n    - BLAKE2B160\r\n    - BLAKE2B224E\r\n    - BLAKE2B224\r\n    - BLAKE2B384E\r\n    - BLAKE2B384\r\n    - BLAKE2BP512E\r\n    - BLAKE2BP512\r\n    - BLAKE2S256E\r\n    - BLAKE2S256\r\n    - BLAKE2S160E\r\n    - BLAKE2S160\r\n    - BLAKE2S224E\r\n    - BLAKE2S224\r\n    - BLAKE2SP256E\r\n    - BLAKE2SP256\r\n    - BLAKE2SP224E\r\n    - BLAKE2SP224\r\n    - SHA1E\r\n    - SHA1\r\n    - MD5E\r\n    - MD5\r\n    - WORM\r\n    - URL\r\n  - local repository version: 5\r\n  - operating system: linux x86_64\r\n  - remote types: \r\n    - git\r\n    - gcrypt\r\n    - p2p\r\n    - S3\r\n    - bup\r\n    - directory\r\n    - rsync\r\n    - web\r\n    - bittorrent\r\n    - webdav\r\n    - adb\r\n    - tahoe\r\n    - glacier\r\n    - ddar\r\n    - git-lfs\r\n    - hook\r\n    - external\r\n  - supported repository versions: \r\n    - 5\r\n    - 7\r\n  - upgrade supported from repository versions: \r\n    - 0\r\n    - 1\r\n    - 2\r\n    - 3\r\n    - 4\r\n    - 5\r\n    - 6\r\n  - version: 7.20190819+git2-g908476a9b-1~ndall+1\r\n## location \r\n  - path: /data/bbx/repositories/rede-mocambos-123456\r\n  - type: dataset\r\n## metadata_extractors \r\n  - annex (datalad 0.14.0): \r\n    - distribution: datalad 0.14.0\r\n    - load_error: None\r\n    - module: datalad.metadata.extractors.annex\r\n    - version: None\r\n  - audio (datalad 0.14.0): \r\n    - distribution: datalad 0.14.0\r\n    - load_error: None\r\n    - module: datalad.metadata.extractors.audio\r\n    - version: None\r\n  - datacite (datalad 0.14.0): \r\n    - distribution: datalad 0.14.0\r\n    - load_error: None\r\n    - module: datalad.metadata.extractors.datacite\r\n    - version: None\r\n  - datalad_core (datalad 0.14.0): \r\n    - distribution: datalad 0.14.0\r\n    - load_error: None\r\n    - module: datalad.metadata.extractors.datalad_core\r\n    - version: None\r\n  - datalad_rfc822 (datalad 0.14.0): \r\n    - distribution: datalad 0.14.0\r\n    - load_error: None\r\n    - module: datalad.metadata.extractors.datalad_rfc822\r\n    - version: None\r\n  - exif (datalad 0.14.0): \r\n    - distribution: datalad 0.14.0\r\n    - load_error: None\r\n    - module: datalad.metadata.extractors.exif\r\n    - version: None\r\n  - frictionless_datapackage (datalad 0.14.0): \r\n    - distribution: datalad 0.14.0\r\n    - load_error: None\r\n    - module: datalad.metadata.extractors.frictionless_datapackage\r\n    - version: None\r\n  - image (datalad 0.14.0): \r\n    - distribution: datalad 0.14.0\r\n    - load_error: None\r\n    - module: datalad.metadata.extractors.image\r\n    - version: None\r\n  - xmp (datalad 0.14.0): \r\n    - distribution: datalad 0.14.0\r\n    - load_error: None\r\n    - module: datalad.metadata.extractors.xmp\r\n    - version: None\r\n## metadata_indexers \r\n## python \r\n  - implementation: CPython\r\n  - version: 3.7.3\r\n## system \r\n  - distribution: LinuxMint/4/debbie\r\n  - encoding: \r\n    - default: utf-8\r\n    - filesystem: utf-8\r\n    - locale.prefered: UTF-8\r\n  - max_path_length: 320\r\n  - name: Linux\r\n  - release: 4.19.0-14-amd64\r\n  - type: posix\r\n  - version: #1 SMP Debian 4.19.171-2 (2021-01-30)\r\n</details>\r\n\r\n\r\n#### Is there anything else that would be useful to know in this context?\r\n\r\nThat's the python log:\r\n\r\n```\r\n[Level 2] Entered eval_func for <function Save.__call__ at 0x7fd18b6bc7b8> \r\nEntered eval_func for <function Save.__call__ at 0x7fd18b6bc7b8>\r\n[DEBUG  ] Determined class of decorated function: <class 'datalad.core.local.save.Save'> \r\nDetermined class of decorated function: <class 'datalad.core.local.save.Save'>\r\n[Level 5] Detected <class 'datalad.support.annexrepo.AnnexRepo'> at /data/bbx/repositories/rede-mocambos-123456 \r\nDetected <class 'datalad.support.annexrepo.AnnexRepo'> at /data/bbx/repositories/rede-mocambos-123456\r\n[Level 5] Requested to provide version for cmd:git \r\nRequested to provide version for cmd:git\r\n[Level 5] Requested to provide version for cmd:git \r\nRequested to provide version for cmd:git\r\n[Level 5] Found 0 previous connections \r\nFound 0 previous connections\r\n[DEBUG  ] Async run ['git', 'config', '-z', '-l', '--show-origin'] \r\nAsync run ['git', 'config', '-z', '-l', '--show-origin']\r\n[DEBUG  ] Launching process ['git', 'config', '-z', '-l', '--show-origin'] \r\nLaunching process ['git', 'config', '-z', '-l', '--show-origin']\r\n[DEBUG  ] Process 31813 started \r\nProcess 31813 started\r\n[DEBUG  ] Waiting for process 31813 to complete \r\nWaiting for process 31813 to complete\r\n[Level 5] Read 400 bytes from 31813[stdout] \r\nRead 400 bytes from 31813[stdout]\r\n```\r\n\r\n\r\nwith process 31813 beeing:\r\n`[git] <defunct>`\r\n\r\n#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)\r\nI've been experiencing a bit. I already use git-annex and we made a software, Baob\u00e1xia, based on it. \r\nWe would like to use datalad in a new version/implementation of Baob\u00e1xia.\r\n\r\nThanks!\r\n", "closed_by": {"login": "20", "id": 921216, "node_id": "MDQ6VXNlcjkyMTIxNg==", "avatar_url": "https://avatars.githubusercontent.com/u/921216?v=4", "gravatar_id": "", "url": "https://api.github.com/users/20", "html_url": "https://github.com/20", "followers_url": "https://api.github.com/users/20/followers", "following_url": "https://api.github.com/users/20/following{/other_user}", "gists_url": "https://api.github.com/users/20/gists{/gist_id}", "starred_url": "https://api.github.com/users/20/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/20/subscriptions", "organizations_url": "https://api.github.com/users/20/orgs", "repos_url": "https://api.github.com/users/20/repos", "events_url": "https://api.github.com/users/20/events{/privacy}", "received_events_url": "https://api.github.com/users/20/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/5482/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/5482/timeline", "performed_via_github_app": null}