{"url": "https://api.github.com/repos/datalad/datalad/issues/5765", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/5765/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/5765/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/5765/events", "html_url": "https://github.com/datalad/datalad/issues/5765", "id": 930266021, "node_id": "MDU6SXNzdWU5MzAyNjYwMjE=", "number": 5765, "title": "create-siblings-ria recursively crashes, non git-annex repo?", "user": {"login": "bpinsard", "id": 1155388, "node_id": "MDQ6VXNlcjExNTUzODg=", "avatar_url": "https://avatars.githubusercontent.com/u/1155388?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bpinsard", "html_url": "https://github.com/bpinsard", "followers_url": "https://api.github.com/users/bpinsard/followers", "following_url": "https://api.github.com/users/bpinsard/following{/other_user}", "gists_url": "https://api.github.com/users/bpinsard/gists{/gist_id}", "starred_url": "https://api.github.com/users/bpinsard/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bpinsard/subscriptions", "organizations_url": "https://api.github.com/users/bpinsard/orgs", "repos_url": "https://api.github.com/users/bpinsard/repos", "events_url": "https://api.github.com/users/bpinsard/events{/privacy}", "received_events_url": "https://api.github.com/users/bpinsard/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2021-06-25T15:11:22Z", "updated_at": "2021-06-25T15:11:22Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "#### What is the problem?\r\n\r\nI am trying to recursively create a RIA siblings on a nested dataset and it fails with the following error.\r\n\r\n```\r\n[ERROR  ] RIA URI not recognized, no valid dataset ID or other supported scheme: ria+file:///project/.../.../ria-beluga/#None [clone.py:decode_source_spec:1208] (ValueError) \r\n```\r\n\r\nIs that because one of the nested dataset is a regular git submodule (without git-annex) and as such it is missing a UUID that would be used to generate the URL ?\r\n\r\nThanks.\r\n\r\n#### What steps will reproduce the problem?\r\nTrying to create a sibling for a pure-git repo? \r\n\r\n#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?\r\n0.14.0\r\n#### Is there anything else that would be useful to know in this context?\r\n#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)\r\nYes!! \r\n", "closed_by": null, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/5765/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/5765/timeline", "performed_via_github_app": null}